// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUa6UZchRvlZDWGSHM6lnXHhC6c8h1ik',
    appId: '1:594758831045:web:4fabd8d38db3dcba1c99ac',
    messagingSenderId: '594758831045',
    projectId: 'boxtout-backend-project',
    authDomain: 'boxtout-backend-project.firebaseapp.com',
    storageBucket: 'boxtout-backend-project.appspot.com',
    measurementId: 'G-H79HSSYY56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5pp-zfCZS46DHsbUAMryqNw7ZYg5leM',
    appId: '1:594758831045:android:c0c0a53da6d0d88f1c99ac',
    messagingSenderId: '594758831045',
    projectId: 'boxtout-backend-project',
    storageBucket: 'boxtout-backend-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWd-3NnyilH4p-1xGcI8E8JHEUL4HQGXQ',
    appId: '1:594758831045:ios:7dda05d7303f6c931c99ac',
    messagingSenderId: '594758831045',
    projectId: 'boxtout-backend-project',
    storageBucket: 'boxtout-backend-project.appspot.com',
    androidClientId: '594758831045-gbpphjp3dmaoqqsn1grrl184lvblnoa2.apps.googleusercontent.com',
    iosClientId: '594758831045-s811l02iv8jn20qob2j81fnh2g4nfqg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.customers',
  );
}
