// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrBEnvw64rGgBeVWnnKuknm6HZfjrCqo',
    appId: '1:867409121051:web:2ecc681d4dd6c1327bcdbe',
    messagingSenderId: '867409121051',
    projectId: 'fir-emulators-bb94c',
    authDomain: 'fir-emulators-bb94c.firebaseapp.com',
    storageBucket: 'fir-emulators-bb94c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgm20UH2WK3YgdkZBz6Q2cDgN-p_rUuI',
    appId: '1:867409121051:android:860415e8b7df63fe7bcdbe',
    messagingSenderId: '867409121051',
    projectId: 'fir-emulators-bb94c',
    storageBucket: 'fir-emulators-bb94c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8V9EHWqhgrQ2ih0c2CjAjXnoro2Kkcc',
    appId: '1:867409121051:ios:844a0388376b52747bcdbe',
    messagingSenderId: '867409121051',
    projectId: 'fir-emulators-bb94c',
    storageBucket: 'fir-emulators-bb94c.appspot.com',
    iosClientId: '867409121051-b6dr25gumlcfh86m9f2c8vk4oh1i3s12.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEmulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp8V9EHWqhgrQ2ih0c2CjAjXnoro2Kkcc',
    appId: '1:867409121051:ios:844a0388376b52747bcdbe',
    messagingSenderId: '867409121051',
    projectId: 'fir-emulators-bb94c',
    storageBucket: 'fir-emulators-bb94c.appspot.com',
    iosClientId: '867409121051-b6dr25gumlcfh86m9f2c8vk4oh1i3s12.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEmulator',
  );
}
